
modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="CraftTweaker GUI"
logoFile="logo.png"
authors="Bommels05"
displayTest="IGNORE_ALL_VERSION"
description='''Recipe editing GUI for CraftTweaker'''

[[mixins]]
config="ctgui.mixins.json"

[[dependencies."${mod_id}"]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies."${mod_id}"]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies."${mod_id}"]]
    modId="jei"
    type="optional"
    versionRange="[17.3.0.49,)"
    ordering="AFTER"
    side="CLIENT"
[[dependencies."${mod_id}"]]
    modId="emi"
    type="optional"
    versionRange="[1.1.6+1.20.4+neoforge,)"
    ordering="AFTER"
    side="CLIENT"
[[dependencies."${mod_id}"]]
    modId="crafttweaker"
    type="required"
    versionRange="[17.0.13,)"
    ordering="AFTER"
    side="CLIENT"
[[dependencies."${mod_id}"]]
    modId="mekanism"
    type="optional"
    versionRange="[10.5.10.32,)"
    ordering="AFTER"
    side="CLIENT"
