architectury {
    common(enabled_platforms.split(","))
}

loom {
    accessWidenerPath = file("src/main/resources/ctgui.accesswidener")
}

dependencies {
    modCompileOnly("net.fabricmc:fabric-loader:${fabric_loader_version}")

    compileOnly("dev.emi:emi-neoforge:${emi_version}")
    compileOnly("mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}")
    compileOnly("com.blamejared.crafttweaker:CraftTweaker-neoforge-${minecraft_version}:${crafttweaker_version}") {
        transitive = false
    }

    modCompileOnly("curse.maven:alloy-forgery-438718:5611901")
    modCompileOnly("vectorwing:FarmersDelight:${minecraft_version}-${farmers_delight_fabric_version}+refabricated") {
        transitive = false
    }
}