architectury {
    common(enabled_platforms.split(","))
}

loom {
    accessWidenerPath = file("src/main/resources/ctgui.accesswidener")
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"

    modImplementation "dev.emi:emi-fabric:${emi_version}"
    modImplementation "mezz.jei:jei-${minecraft_version}-fabric:${jei_version}"
    modImplementation("com.blamejared.crafttweaker:CraftTweaker-fabric-${minecraft_version}:${crafttweaker_version}") {
        transitive = false
    }
}