
modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="CraftTweaker GUI"
logoFile="logo.png"
authors="Bommels05"
displayTest="IGNORE_ALL_VERSION"
description='''Recipe editing GUI for CraftTweaker'''

[[mixins]]
config="ctgui.mixins.json"

[[dependencies."${mod_id}"]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies."${mod_id}"]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"
[[dependencies."${mod_id}"]]
    modId="jei"
    type="optional"
    versionRange="[${min_jei_version},)"
    ordering="AFTER"
    side="CLIENT"
[[dependencies."${mod_id}"]]
    modId="emi"
    type="optional"
    versionRange="[${min_emi_neo_version},)"
    ordering="AFTER"
    side="CLIENT"
[[dependencies."${mod_id}"]]
    modId="crafttweaker"
    type="required"
    versionRange="[${min_crafttweaker_version},)"
    ordering="AFTER"
    side="CLIENT"
[[dependencies."${mod_id}"]]
    modId="mekanism"
    type="optional"
    versionRange="[${min_mekanism_version},)"
    ordering="AFTER"
    side="CLIENT"
